---

- hosts: all

  vars:
    repo_url: 'https://github.com/Nagasaki45/Web-Audio.git'
    site_folder: '/home/{{ ansible_ssh_user }}/sites/{{ inventory_hostname }}'
    required_subfolders:
      - source
      - virtualenv

  #########################################################

  tasks:

    #######################################################
    #                 Provisioning                        #
    #######################################################

    - name: make sure required packages are installed
      apt: pkg=nginx,git,python3,python3-pip state=present
      sudo: yes

    - name: make sure virtualenv is installed
      pip: name=virtualenv executable=pip3
      sudo: yes

    - name: add nginx configurations to sites-available
      template: src=./nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ inventory_hostname }}
      sudo: yes
      notify:
        - restart nginx

    - name: add symlink in sites-enabled
      file: src=/etc/nginx/sites-available/{{ inventory_hostname }}
            dest=/etc/nginx/sites-enabled/{{ inventory_hostname }} state=link
      sudo: yes
      notify:
        - restart nginx

    - name: add tornado upstart configurations to init
      template: src=./tornado-upstart.conf.j2
                dest=/etc/init/tornado-{{ inventory_hostname }}.conf
      sudo: yes

    - name: make sure nginx is running
      service: name=nginx state=running
      sudo: yes

    #######################################################
    #                 Deployment                          #
    #######################################################

    - name: create directory structure if necessary
      file: path={{ site_folder }}/{{ item }} state=directory
      with_items: required_subfolders

    - name: get source from github
      git: repo={{ repo_url }}
           dest={{ site_folder }}/source/
           accept_hostkey=yes

    - name: update virtualenv
      pip: virtualenv={{ site_folder }}/virtualenv
           requirements={{ site_folder }}/source/requirements.txt

    - name: reload tornado
      service: name=tornado-{{ inventory_hostname }} state=restarted
      sudo: yes

  #########################################################

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      sudo: yes
